name: CI
on:
  push:
    branches-ignore:
      - 'releases/**'
    tags-ignore:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Get graddle wrapper
      run: ./gradlew wrapper
    - name: Test and Build with Gradle
      run: ./gradlew clean check shadowJar
